import React from "react";


const individualListing = () => {

    const queryString = window.location.search;
    console.log(queryString);
    const urlParams = new URLSearchParams(queryString);
    var uid = urlParams.get('UID');

    var url;
            const server = "http://localhost:8118";
            url = `${server}/getlisting/`;
            const requestOptions = {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify([uid])
            }
            fetch(url, requestOptions)
                .then((response => response.text()
                    .then(id => {
                        //id is the autogenerated Firestore ID of the listing.
                        //use this ID as reference in S3 images maybe?
                        console.log("response id: ", id);

                    })))

    return (
        <div>
            <h2>About Us {uid}</h2>
        </div>
    );
}

export default individualListing;
