import React, { useState } from "react";

import { Form, Button, Modal, FormGroup, FormControl, ControlLabel } from "react-bootstrap";




const SignUp = () => {
    //https://react-bootstrap.github.io/components/modal/
    const [show, setShow] = useState(false);

    const handleClose = () => setShow(false);
    const handleShow = () => setShow(true);
    var isClient = false;

    const [form, setForm] = useState({
        active: true,
        name: "",
        email: "",
        password: "",
    });

    const handleChange = (e) => {
            const curOpt = e.target.value;
            if(curOpt === "Client"){
                isClient = true;
            }
            else if(curOpt === "Contractor"){
                isClient = false;
            }
    }

    const handleSubmit = () => {
        if (false) {
            alert("Listing title and description must be filled out");
        }
        else {
            var url;
            const server = "http://localhost:8118";
            if(!isClient)
                url = `${server}/addcontractor/`;
            else if(isClient)
                url = `${server}/addclient/`;
            const requestOptions = {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify(form)
            }
            fetch(url, requestOptions)
                .then((response => response.text()
                    .then(id => {
                        //id is the autogenerated Firestore ID of the listing.
                        //use this ID as reference in S3 images maybe?
                        console.log("response id: ", id);

                    })));
        }
        handleClose();
    }
    
    return (
        <div>
            <Button className="sign-button" variant="primary" onClick={handleShow}>
                Sign Up
          </Button>

            <Modal show={show} onHide={handleClose}>
                <Modal.Header closeButton>
                    <Modal.Title>Sign Up Here</Modal.Title>
                </Modal.Header>
                <Modal.Body>
                <Form>
                   
                    <Form.Group controlId="name">
                        <Form.Label>First and Last Name</Form.Label>
                        <Form.Control type="name" field="name" placeholder="Enter Name" />
                        
                    </Form.Group>
                    <Form.Group controlId="email">
                        <Form.Label>Email Address</Form.Label>
                        <Form.Control type="text" placeholder="Enter Email" />
                        <Form.Text className="text-muted">
                            We'll never share your email with anyone else.
                        </Form.Text>
                    </Form.Group>

                    <Form.Group controlId="password">
                        <Form.Label>Password</Form.Label>
                        <Form.Control type="password" field="password" placeholder="Password" />
                    </Form.Group>
                    <Form.Group>
                        <Form.Label>Select document type</Form.Label>
                        <Form.Control as="select">
                            <option>Contractor</option>
                            <option>Client</option>
                        </Form.Control>

                    </Form.Group>
                </Form>
                </Modal.Body>
                <Modal.Footer>
                    <Button variant="secondary" onClick={handleClose}>
                        Close
              </Button>
                    <Button variant="primary" onClick={handleSubmit}>
                        Sign Up
              </Button>
                </Modal.Footer>
            </Modal>
        </div>
    );
};

export default SignUp;